import type { NavigationMenu } from "@/types/navigation";

export const FALLBACK_NAVIGATION_MENU: NavigationMenu = {
  id: "fallback-main-navigation",
  name: "main",
  displayName: "Main Navigation",
  type: "main",
  items: [
    {
      id: "nav-home",
      label: "Home",
      url: "/",
      icon: "home",
      description: "Return to the New India Timber homepage",
      order: 1,
      isExternal: false,
      isVisible: true,
    },
    {
      id: "nav-products",
      label: "Products",
      url: "/products",
      icon: "package",
      description: "Premium timber solutions for Bangalore projects",
      order: 2,
      isExternal: false,
      isVisible: true,
      children: [
        {
          id: "nav-products-teak",
          label: "Teak Wood",
          url: "/products?category=teak",
          icon: "tree-pine",
          description: "Imported and local teak varieties",
          order: 1,
          isExternal: false,
          isVisible: true,
          children: [
            {
              id: "nav-products-teak-burma",
              label: "Burma Teak",
              url: "/products/burma-teak-door",
              order: 1,
              isExternal: false,
              isVisible: true,
            },
            {
              id: "nav-products-teak-ghana",
              label: "Ghana Teak",
              url: "/products/ghana-teak-window",
              order: 2,
              isExternal: false,
              isVisible: true,
            },
            {
              id: "nav-products-teak-benin",
              label: "Benin Teak Logs",
              url: "/products/benin-teak-logs",
              order: 3,
              isExternal: false,
              isVisible: true,
            },
            {
              id: "nav-products-teak-tanzania",
              label: "Tanzania Teak Wood",
              url: "/products/tanzania-teak-wood",
              order: 4,
              isExternal: false,
              isVisible: true,
            },
          ],
        },
        {
          id: "nav-products-plywood",
          label: "Plywood",
          url: "/products?category=plywood",
          icon: "layers",
          description: "Marine grade, commercial, and premium plywood",
          order: 2,
          isExternal: false,
          isVisible: true,
          children: [
            {
              id: "nav-products-plywood-century",
              label: "Century Ply Sainik MR 18mm",
              url: "/products/century-ply-sainik-mr-18mm",
              order: 1,
              isExternal: false,
              isVisible: true,
            },
            {
              id: "nav-products-plywood-marine",
              label: "Marine Grade",
              url: "/products/marine-plywood-19mm",
              order: 2,
              isExternal: false,
              isVisible: true,
            },
          ],
        },
        {
          id: "nav-products-hardwood",
          label: "Hardwood Logs",
          url: "/products?category=hardwood",
          icon: "logs",
          description: "Structural hardwood logs sourced within Karnataka",
          order: 3,
          isExternal: false,
          isVisible: true,
          children: [
            {
              id: "nav-products-hardwood-red-sal",
              label: "Red Sal Wood",
              url: "/products/red-sal-wood",
              order: 1,
              isExternal: false,
              isVisible: true,
            },
            {
              id: "nav-products-hardwood-australia-honne",
              label: "Australia Honne Wood",
              url: "/products/australia-honne-wood",
              order: 2,
              isExternal: false,
              isVisible: true,
            },
            {
              id: "nav-products-hardwood-red-meranti",
              label: "Red Meranti Sal Wood",
              url: "/products/red-meranti-sal-wood",
              order: 3,
              isExternal: false,
              isVisible: true,
            },
            {
              id: "nav-products-hardwood-mahogany",
              label: "Mahogany Wood",
              url: "/products/mahogany-wood",
              order: 4,
              isExternal: false,
              isVisible: true,
            },
            {
              id: "nav-products-hardwood-teak-log",
              label: "Teak Hardwood Log",
              url: "/products/hardwood-log-teak",
              order: 5,
              isExternal: false,
              isVisible: true,
            },
          ],
        },
      ],
    },
    {
      id: "nav-services",
      label: "Services",
      url: "/services",
      icon: "briefcase",
      description: "Bulk orders, custom solutions, and delivery support",
      order: 3,
      isExternal: false,
      isVisible: true,
      children: [
        {
          id: "nav-services-bulk-orders",
          label: "Bulk Orders",
          url: "/bulk-orders",
          icon: "truck",
          order: 1,
          isExternal: false,
          isVisible: true,
        },
        {
          id: "nav-services-custom-solutions",
          label: "Custom Solutions",
          url: "/services/custom",
          icon: "puzzle",
          order: 2,
          isExternal: false,
          isVisible: true,
        },
        {
          id: "nav-services-delivery",
          label: "Delivery",
          url: "/services/delivery",
          icon: "route",
          order: 3,
          isExternal: false,
          isVisible: true,
        },
      ],
    },
    {
      id: "nav-blog",
      label: "Blog",
      url: "/blog",
      icon: "newspaper",
      description: "Insights and guides for Bangalore timber projects",
      order: 4,
      isExternal: false,
      isVisible: true,
      children: [
        {
          id: "nav-blog-timber-tips",
          label: "Timber Tips Bangalore",
          url: "/blog/category/timber-tips-bangalore",
          order: 1,
          isExternal: false,
          isVisible: true,
        },
        {
          id: "nav-blog-design",
          label: "Design Inspiration",
          url: "/blog/category/design-inspiration",
          order: 2,
          isExternal: false,
          isVisible: true,
        },
        {
          id: "nav-blog-sustainability",
          label: "Sustainability",
          url: "/blog/category/sustainability",
          order: 3,
          isExternal: false,
          isVisible: true,
        },
      ],
    },
    {
      id: "nav-about",
      label: "About",
      url: "/about",
      icon: "info",
      order: 5,
      isExternal: false,
      isVisible: true,
    },
    {
      id: "nav-contact",
      label: "Contact",
      url: "/contact",
      icon: "phone",
      order: 6,
      isExternal: false,
      isVisible: true,
    },
    {
      id: "nav-legal",
      label: "Legal",
      url: "/privacy",
      icon: "scale",
      order: 7,
      isExternal: false,
      isVisible: true,
      children: [
        {
          id: "nav-legal-privacy",
          label: "Privacy Policy",
          url: "/privacy",
          order: 1,
          isExternal: false,
          isVisible: true,
        },
        {
          id: "nav-legal-terms",
          label: "Terms & Conditions",
          url: "/terms",
          order: 2,
          isExternal: false,
          isVisible: true,
        },
        {
          id: "nav-legal-refund",
          label: "Refund Policy",
          url: "/refund",
          order: 3,
          isExternal: false,
          isVisible: true,
        },
      ],
    },
  ],
  settings: {
    maxDepth: 3,
    showIcons: true,
    showDescriptions: true,
    mobileCollapsible: true,
    theme: "auto",
  },
  isActive: true,
  version: 1,
  createdAt: "2025-01-01T00:00:00.000Z",
  updatedAt: "2025-01-01T00:00:00.000Z",
};
