export interface SEOSetting {
  page: string; // Changed from pageId to page for consistency
  metaTitle?: string;
  metaDescription?: string;
  keywords?: string[];
  canonicalUrl?: string;
  structuredData?: Record<string, any>;
  openGraph?: {
    title?: string;
    description?: string;
    image?: string;
    type?: string;
    siteName?: string;
  };
  twitterCard?: {
    card?: string;
    title?: string;
    description?: string;
    image?: string;
  };
  robots?: string;
  noindex?: boolean;
  nofollow?: boolean;
}

export interface SEOSettingsCreateRequest {
  page: string;
  metaTitle?: string;
  metaDescription?: string;
  keywords?: string[];
  canonicalUrl?: string;
  structuredData?: Record<string, any>;
  openGraph?: {
    title?: string;
    description?: string;
    image?: string;
    type?: string;
    siteName?: string;
  };
  twitterCard?: {
    card?: string;
    title?: string;
    description?: string;
    image?: string;
  };
  robots?: string;
  noindex?: boolean;
  nofollow?: boolean;
}

export interface SEOSettingsUpdateRequest {
  metaTitle?: string;
  metaDescription?: string;
  keywords?: string[];
  canonicalUrl?: string;
  structuredData?: Record<string, any>;
  openGraph?: {
    title?: string;
    description?: string;
    image?: string;
    type?: string;
    siteName?: string;
  };
  twitterCard?: {
    card?: string;
    title?: string;
    description?: string;
    image?: string;
  };
  robots?: string;
  noindex?: boolean;
  nofollow?: boolean;
}

export interface SitemapEntry {
  url: string;
  lastModified: string;
  changeFrequency: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';
  priority: number;
}

export interface SitemapConfig {
  baseUrl: string;
  entries: SitemapEntry[];
  lastGenerated: string;
}

export interface SEOAnalysisResult {
  score: number;
  issues: SEOIssue[];
  recommendations: SEORecommendation[];
  metadata: {
    title?: string;
    description?: string;
    keywords?: string[];
    canonical?: string;
  };
}

export interface SEOIssue {
  type: 'error' | 'warning' | 'info';
  message: string;
  field?: string;
  suggestion?: string;
}

export interface SEORecommendation {
  priority: 'high' | 'medium' | 'low';
  title: string;
  description: string;
  action?: string;
}

// Additional types for seoStorage compatibility
export interface GlobalSEOSettings {
  siteName: string;
  siteDescription: string;
  defaultMetaTitle: string;
  defaultMetaDescription: string;
  defaultKeywords: string[];
  defaultImage: string;
  twitterHandle?: string;
  facebookAppId?: string;
}

export interface PageSEOSettings {
  page: string;
  metaTitle?: string;
  metaDescription?: string;
  keywords?: string[];
  canonicalUrl?: string;
  structuredData?: Record<string, any>;
  openGraph?: {
    title?: string;
    description?: string;
    image?: string;
    type?: string;
    siteName?: string;
  };
  twitterCard?: {
    card?: string;
    title?: string;
    description?: string;
    image?: string;
  };
  robots?: string;
  noindex?: boolean;
  nofollow?: boolean;
}

export interface AISettings {
  enabled: boolean;
  autoGenerateDescriptions: boolean;
  autoGenerateKeywords: boolean;
  autoGenerateTitles: boolean;
  language: string;
  tone: string;
  maxLength: number;
}

// Default values
export const defaultGlobalSEOSettings: GlobalSEOSettings = {
  siteName: "New India Timber",
  siteDescription: "Premium timber and wood suppliers in Bangalore, Karnataka",
  defaultMetaTitle: "New India Timber - Premium Wood Suppliers Bangalore",
  defaultMetaDescription: "Leading timber suppliers in Bangalore offering premium quality wood, teak, and construction materials.",
  defaultKeywords: ["timber", "wood", "bangalore", "karnataka", "construction", "teak"],
  defaultImage: "/images/logo.png",
  twitterHandle: "@newindiatimber",
  facebookAppId: ""
};

export const predefinedPages = [
  "home",
  "products",
  "about",
  "contact",
  "blog",
  "services"
];

export const defaultAISettings: AISettings = {
  enabled: true,
  autoGenerateDescriptions: true,
  autoGenerateKeywords: true,
  autoGenerateTitles: false,
  language: "en",
  tone: "professional",
  maxLength: 160
};